import Head from 'next/head';

import CategoryTabs from '../components/CategoryTabs/CategoryTabs';
import Contacts from '../components/Contacts/Contacts';
import Headline from '../components/Headline/Headline';
import Products from '../components/Products/Products';
import SpanbondDescription from '../components/SpanbondDescription/SpanbondDescription';

import styles from '../styles/Home.module.scss';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Спанчбонд - Нетканные материалы</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>
        <Headline />
        <SpanbondDescription />
        <Products />
        <CategoryTabs />
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 196" fill="none">
        <path fillRule="evenodd" clipRule="evenodd" d="M1440 0H0V195.029C215.554 101.063 460.188 48 719.5 48C979.213 48 1224.2 101.227 1440 195.466V0Z" fill="#FFFFFF" />
      </svg>
      <Contacts />
    </div>
  )
}

export default Home;
