import Head from "next/head";
import ImageComponent from "../../components/ImageComponent/ImageComponent";

import styles from './aboutus.module.scss';

const AboutUs = () => {
    return (
        <>
            <Head>
                <title>О нашей компании</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.content}>
                    <div className={styles.image}>
                        <ImageComponent
                            src={'/images/image 13.png'}
                            alt="Спандбонд"
                        />
                    </div>
                    <div className={styles.description}>
                        <h2>О нашей компании</h2>
                        <div>
                            <p>Спанбонд (англ. spunbond) — название технологии производства нетканого материала из расплава полимера фильерным способом. В профессиональной области так называют и сам материал, который производят по описанной технологии.</p>
                            <p>Наиболее часто для производства «спанбонда» используется полипропилен, поскольку он позволяет получать наиболее плотное распределение волокон в холсте и обеспечивает высокую выработку волокон в перерасчёте на килограмм сырья. </p>
                            <p>Толщина спанбонда определяется его назначением и способом производства, так как от толщины зависит его воздухопроницаемость, жёсткость, теплоизоляционные свойства.</p>
                        </div>
                    </div>
                </div>
                <div className={styles.vector1}>
                    <ImageComponent
                        src={'/images/about-us-vector-1.png'}
                        alt=""
                    />
                </div>
                <div className={styles.vector2}>
                    <ImageComponent
                        src={'/images/about-us-vector-2.png'}
                        alt=""
                    />
                </div>
                <div className={styles.vector3}>
                    <ImageComponent
                        src={'/images/about-us-vector-3.png'}
                        alt=""
                    />
                </div>
            </div>
        </>
    );
}

export default AboutUs;